name: "Build and Apply a Prefect deployment from a flow"
on:
  push: # or on changes to paths in branches
    branches:
      - "main"
    paths:
      - "flow.py"

# change as needed
env:
  DEPLOYMENT_NAME: my-deployment
  FLOW_FILE: flow.py
  ENTRYPOINT: api_flow
  FILESYSTEM_EXTRAS: gcsfs
  STORAGE_BLOCK: github/prefect-docker
  WORK_QUEUE: agent
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
  PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

jobs:
  prefect-deployment-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Update Pip and required filesystem extras
        run: pip install -U wheel pip $FILESYSTEM_EXTRAS

      - name: Add Flow Dependencies (including Prefect)
        run: pip install -r requirements.txt

      - name: Build / Apply deployment
        run: |
          prefect deployment build ./$FLOW_FILE:$ENTRYPOINT --name $DEPLOYMENT_NAME -sb $STORAGE_BLOCK --work-queue $WORK_QUEUE --apply

      - name: Output Success
        run: echo "Successfully built and applied ${{ env.DEPLOYMENT_NAME }} :rocket:" >> $GITHUB_STEP_SUMMARY
